### ISSUE TITLE
Retry requests that failed due to transient network issues

### ISSUE THREAD

**Issue by JulijaRamoskiene** [iTwin/insights-client#79]
Retry requests when they failed due to transient network error. Currently only requests with 429 responses are retried here: https://github.com/iTwin/insights-client/blob/main/src/common/OperationsBase.ts

 Sample of request that should be re-tried:
![Image](https://github.com/user-attachments/assets/cb34fd52-dd3a-4a7c-b0a2-336004b52444)

Suggested error and status codes for re-try:

**StatusCodes:** 408, 413, 429, 500, 502, 503, 504, 521, 522, 524

**ErrorCodes:** "ETIMEDOUT", "ECONNRESET", "EADDRINUSE", "ECONNREFUSED", "EPIPE", "ENOTFOUND", "ENETUNREACH", "EAI_AGAIN", "ECONNABORTED"

**Comment by MindaugasButkus** [comment]
Will not add retries for 413 (Content Too Large) - retrying will not reduce the content size.

**Comment by MindaugasButkus** [comment]
Version 0.15.0 published with this change.
